//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Muktas.ERP.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class City : BaseModel
    {
        public System.Guid CityId { get; set; }
        [Required]
        public System.Guid StateId { get; set; }
        [Required]
        [MaxLength(50)]
        public string CityName { get; set; }
        [Required]
        [MaxLength(10)]
        public string Pincode { get; set; }

        public State State { get; set; }
    }
}
