//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Muktas.ERP.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class State : BaseModel
    {
        public System.Guid StateId { get; set; }
        [Required]
        [MaxLength(2)]
        public string StateCode { get; set; }
        [Required]
        [MaxLength(50)]
        public string StateName { get; set; }
        [Required]
        public System.Guid CountryId { get; set; }
        [Required]
        [Range(1,999)]
        public int StateVatTinNo { get; set; }
        public Country Country { get; set; }
    }
}
